services:
  district4-prod-test:
    image: district4-tool-main-district4:latest

    container_name: district4-prod-test

    env_file:
      - .env

    environment:
      TZ: Asia/Manila
      PYTHONUNBUFFERED: "1"

    ports:
      - "5001:8000"

    volumes:
      - ./.env:/app/.env:ro
      - ./service_account.json:/app/service_account.json:ro
      - ./app_v2.db:/app/app_v2.db
      - ./ai_index.db:/app/ai_index.db
      - ./generated_reports:/app/generated_reports

    command: >
      gunicorn
      --bind 0.0.0.0:8000
      --workers 1
      --threads 4
      --timeout 180
      --access-logfile -
      --error-logfile -
      app:app